name: PublishTest

on:
  workflow_dispatch:
    inputs:
      new-version:
        required: true
        description: New plugin version e.g. 1.0

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 1
  update-samples:
    needs: publish
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 1
      - name: Trigger library updates in each repo
        uses: actions/github-script@v7
        with:
          github-token: ${{ secrets.PAT_GITHUB }}
          script: |
            try {
              const fs = require('fs');
              const jsonString = fs.readFileSync('./.github/workflows/sample-projects.json');
              const sampleProjects = JSON.parse(jsonString);
              console.log(sampleProjects);
              sampleProjects.forEach((sampleProject) => {
                console.log('Triggering update for: ' + sampleProject.repo);
                github.rest.actions.createWorkflowDispatch({
                  owner: sampleProject.owner,
                  repo: sampleProject.repo,
                  workflow_id: 'update-generator-version.yaml',
                  ref: sampleProject.default_branch,
                  inputs: {
                    'new-version': "${{ inputs.new-version }}"
                  },
                });
              });
            } catch(err) {
              core.error("Error while reading or parsing the JSON");
              core.setFailed(err);
            }
