name: Update Samples

on:
  workflow_run:
    workflows: [ 'PublishTest' ]
    types: [ completed ]
    branches:
      - 'master'

jobs:
  build:
    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    steps:
      - name: checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 1
      - name: Trigger library updates in each repo
        uses: actions/github-script@v7
        with:
          script: |
            console.log(context)
            try {
              const fs = require('fs');
              const jsonString = fs.readFileSync('./.github/workflows/sample-projects.json');
              const sampleRepos = JSON.parse(jsonString);
              console.log(sampleRepos);
              sampleRepos.forEach((sampleRepo) => {
                console.log('repo: ' + sampleRepo);
              });
            } catch(err) {
              core.error("Error while reading or parsing the JSON");
              core.setFailed(err);
            }
