name: Verify

#on: [ push, workflow_dispatch, pull_request ]
on: [ workflow_dispatch ]
env:
  XCODE_VERSION: '15.0.1'
  JAVA_VERSION: '17'

jobs:
  build:
    runs-on: macOS-13
    steps:
      - name: checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 1
      - name: Setup XCode
        uses: maxim-lobanov/setup-xcode@v1
        with:
          xcode-version: ${{ env.XCODE_VERSION }}
      - name: Setup JDK
        uses: actions/setup-java@v4
        with:
          java-version: |
            8
            ${{ env.JAVA_VERSION }}
          distribution: "zulu"
      - name: Cache build tooling
        uses: actions/cache@v4
        with:
          path: |
            ~/.konan
          key: ${{ runner.os }}-v4-${{ hashFiles('*.gradle.kts') }}
      - name: Build Plugin & Runtime
        run: |
          ./gradlew -version --no-daemon
          ./gradlew check publishToMavenLocal --no-daemon --stacktrace
        env:
          GRADLE_OPTS: -Dkotlin.incremental=false -Dorg.gradle.jvmargs="-Xmx3g -XX:+HeapDumpOnOutOfMemoryError -Dfile.encoding=UTF-8 -XX:MaxMetaspaceSize=512m"
      - name: Archive test results
        uses: actions/upload-artifact@v4
        if: always()
        with:
          name: junit-test-results
          path: '**/build/test-results/test/TEST-*.xml'
          retention-days: 1
      - name: Build KMP Sample app (shared, Android, JVM, JS)
        working-directory: ./samples/SampleKMPApplication
        run: ./gradlew check --no-daemon --stacktrace
        env:
          GRADLE_OPTS: -Dkotlin.incremental=false -Dorg.gradle.jvmargs="-Xmx3g -XX:+HeapDumpOnOutOfMemoryError -Dfile.encoding=UTF-8 -XX:MaxMetaspaceSize=512m"
      - name: Build iOS Sample app
        working-directory: ./samples/SampleKMPApplication
        run: xcodebuild build -project iosApp/iosApp.xcodeproj -configuration Debug -scheme iosApp -sdk iphoneos -destination name='iPhone 15 Pro' -verbose
